### ISSUE TITLE
Project is not compilable with TCC

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#1224]

**Comment by Nykseli** [comment]
The problem with pulse audio was that it couldn't find the libpulsecommon-12.2.so that is located under
/usr/lib/x86_64-linux-gnu/pulseaudio.

I don't know why this happens but as a workaround you can get nothing running with:
CC=tcc CFLAGS='-DSDL_DISABLE_IMMINTRIN_H -L/usr/lib/x86_64-linux-gnu/pulseaudio'  ./build-posix.sh

**Comment by rexim** [comment]
@Nykseli bruh! That's epic! Thank you very much! ![](https://static-cdn.jtvnw.net/emoticons/v1/301027670/1.0) :+1:
