### ISSUE TITLE
when console is enabled a backquote pressed event sneaks into edit_field and gets inserted

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#404]
introduced in #403

**Comment by valignatev** [comment]
The main reason for this issue is that SDL spamming 3 consecutive events: keydown, textinput and keyup. Console is being activated upon keydown, and next texinput immediately inserts backtick (or 'c').

The less painful solution will be to enable console upon keyup event, and start listening for textinput only then. I'll provide PR for this.

**Comment by valignatev** [comment]
Another solution would be to discard first textinput event after keydown, but I think it's much more of a hassle. Anyways, even if you won't like my solution, at least I debugged it for you :)
