### ISSUE TITLE
Mark issues with "good first issue" label

### ISSUE THREAD

**Issue by filfreire** [tsoding/nothing#665]
@rexim can you mark some of the current opened issues with `good first issue` label for new contributors to try?

**Comment by rexim** [comment]
@filfreire I personally think such labels are useless. As a new contributor, feel free to try ANY issue:

1. If the issue is unclear, you can just ask a question right in the issue to clearify it.
2. If the issue is too big you can always decompose it according to [Pull Request][pull-requests] Contribution Rules.
3. If the code is unreadable, report it as a bug according to [Issues][issues] Contribution Rules.

[pull-requests]: https://github.com/tsoding/nothing/blob/3986d17dc7eb9959d8ccd59f1e28cf87583cdaf1/CONTRIBUTING.md#pull-requests
[issues]: https://github.com/tsoding/nothing/blob/3986d17dc7eb9959d8ccd59f1e28cf87583cdaf1/CONTRIBUTING.md#issues

**Comment by filfreire** [comment]
@rexim fair enough. Closing this issue 👍
