### ISSUE TITLE
Windows VC build is not strict enough

### ISSUE THREAD

**Issue by rexim** [tsoding/nothing#877]
Enable all warnings and make the errors like in GCC and Clang builds

**Comment by RIscRIpt** [comment]
I suppose you would like to add `/WX` flag (Treat Warnings As Errors).
I've tried to build with this flag and `/Wall` (Enable All Warnings), and I've got the following warnings (which were treated as errors):
```
src\system\line_stream.c(21,1): warning C4820:  'LineStream': '7' bytes padding added after data member 'unfinished'
Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h(828,37): warning C4710:  'int fprintf(FILE *const ,const char *const ,...)': function not inlined
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\immintrin.h(1346,50): warning C4255:  '_readfsbase_u32': no function prototype given: converting '()' to '(void)'
src\ebisp\expr.h(38,6): warning C4201:  nonstandard extension used: nameless struct/union
src\ebisp\expr.h(38,6): warning C4820:  'Expr': '4' bytes padding added after data member 'type'
Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt.h(212,7): warning C4668:  '__cplusplus' is not defined as a preprocessor macro, replacing with '
0
src\ebisp\expr.c(14,1): warning C4204:  nonstandard extension used: non-constant aggregate initializer

... etc
```

According to the [docs](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-option-warning-level?view=vs-2019) `/Wall` enables absolutely all warnings: those which are enabled with `/W` flag ([listed here](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-by-compiler-version?view=vs-2019)), and those which are disabled by default ([listed here](https://docs.microsoft.com/en-us/cpp/preprocessor/compiler-warnings-that-are-off-by-default?view=vs-2019)).
There are too many of them to review and select appropriate, so I guess one of reasonable solutions would be disabling them by demand.

___

Hereby, I propose to disable aforementioned warnings, to make the project build-able using MSVC compiler:

Warning [C4820](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4820?view=vs-2019) seems useless, this project is not networking software, it doesn't require `1:1` struct-to-memory mapping.

Warning [C4668](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4668?view=vs-2019), as there was a [bug](https://developercommunity.visualstudio.com/content/problem/433021/issue-in-corecrth-header-results-in-an-undefined-m.html) in previous versions of Windows SDK. I'm not sure if I have the latest version, but I still have this bug.

Warning [C4201](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4201?view=vs-2019), because it is explicitly allowed by C11, but according to some posts in the internet 😄 
 MSVC is neither C99 nor C11 complaint ([link 1](https://stackoverflow.com/questions/48981823/is-there-any-option-to-switch-between-c99-and-c11-c-standards-in-visual-studio), [link 2](https://www.quora.com/How-can-I-run-c11-or-c99-in-Visual-Studio-2017)).

Warning [C4204](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4204?view=vs-2019), restriction dropped in C99 (according to [this post](https://stackoverflow.com/a/1065193/1901561)).

Warning [C4255](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4255?view=vs-2019). FYI `f()` accepts variable amount of arguments, but `f(void)` accepts no arguments. I'm not sure you'd like to change the whole code base from `f() -> f(void)`. Also there warnings also come from Windows SDK (as you could see in the previous listing).

Warning [C4710](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4710?view=vs-2019). I see no sense in it 😃 (at least for nothing).

Warning [C4777](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4600-through-c4799?view=vs-2019). This seems to be useful flag, but there is [C4477](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4477?view=vs-2019). I disabled it later, because it complained on
```
'fprintf' : format string '%lld' requires an argument of type '__int64', but variadic argument 1 has type
'intmax_t'
```
___

Also there were warnings, which, I suppose should not be disabled:
```
src\ebisp\gc.c(25,36): warning C4311:  'type cast': pointer truncation from 'Cons *' to 'long'
src\ebisp\parser.c(125,1): warning C4244:  'initializing': conversion from 'intmax_t' to 'const long', possible loss of data
src\ebisp\expr.c(51,25): warning C4477:  'fprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'intma
x_t'
src\game\level\goals.c(56,13): warning C4477:  'sscanf' : format string '%lu' requires an argument of type 'unsigned long *', but variadic argument
 1 has type 'size_t *'

... etc
```

Warning [C4311](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4311?view=vs-2019). This warning can be fixed by changing `long int` to `intprt_t`.
Warning [C4244](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244?view=vs-2019). This warning can be fixed by changing `long int` to `intmax_t`.
Warning [C4477](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4477?view=vs-2019). This warning can be fixed by using appropriate formatting, for example changing `%ld` to `"%"PRIdMAX` ([see docs](https://en.cppreference.com/w/c/types/integer)).

___

That's all for now, I decided to stop and share the progress. What do you think? Should I continue and fix all the warnings introduced with `/Wall` and `/WX`?

Here's a sneak peak of warnings left (so far):
```
"R:\projects\c\nothing\build\ALL_BUILD.vcxproj" (default target) (1) ->
"R:\projects\c\nothing\build\nothing.vcxproj" (default target) (5) ->
(ClCompile target) ->
  R:\projects\c\nothing\src\game\level\goals.c(56,13): warning C4477:  'sscanf' : format string '%lu' requires an argument of type 'unsigned long *', but variadic argument
 1 has type 'size_t *' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\labels.c(54,13): warning C4477:  'sscanf' : format string '%lu' requires an argument of type 'unsigned long *', but variadic argumen
t 1 has type 'size_t *' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\lava.c(36,13): warning C4477:  'sscanf' : format string '%lu' requires an argument of type 'unsigned long *', but variadic argument
1 has type 'size_t *' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\regions.c(51,12): warning C4477:  'sscanf' : format string '%lu' requires an argument of type 'unsigned long *', but variadic argume
nt 1 has type 'size_t *' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\rigid_bodies.c(273,32): warning C4477:  'snprintf' : format string '%ld' requires an argument of type 'long', but variadic argument
1 has type 'RigidBodyId' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\sdl\renderer.c(177,43): warning C4127:  conditional expression is constant [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\sdl\renderer.c(210,43): warning C4127:  conditional expression is constant [R:\projects\c\nothing\build\nothing.vcxproj]
R:\projects\c\nothing\src\sdl\renderer.c(210,43): warning C4127: R:\projects\c\nothing\src\math\rect.c(138) : error C2220: warning treated as error - no 'object' file gene
rated [R:\projects\c\nothing\build\nothing.vcxproj]
R:\projects\c\nothing\src\sdl\renderer.c(210,43): warning C4127: R:\projects\c\nothing\src\math\rect.c(138) : warning C4701: potentially uninitialized local variable 'resu
lt' used [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\level_editor\rect_layer.c(92,22): warning C4477:  'sscanf' : format string '%lu' requires an argument of type 'unsigned long *', but
 variadic argument 1 has type 'size_t *' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\level_editor\rect_layer.c(270,23): warning C4477:  'fprintf' : format string '%ld' requires an argument of type 'long', but variadic
 argument 1 has type 'size_t' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\level_editor\layer_picker.c(46,37): warning C4013:  'strlen' undefined; assuming extern returning int [R:\projects\c\nothing\build\n
othing.vcxproj]
  R:\projects\c\nothing\src\game\level\level_editor\point_layer.c(95,13): warning C4477:  'sscanf' : format string '%lu' requires an argument of type 'unsigned long *', bu
t variadic argument 1 has type 'size_t *' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\level_editor\point_layer.c(385,23): warning C4477:  'fprintf' : format string '%ld' requires an argument of type 'long', but variadi
c argument 1 has type 'size_t' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\level_editor\label_layer.c(89,22): warning C4477:  'sscanf' : format string '%lu' requires an argument of type 'unsigned long *', bu
t variadic argument 1 has type 'size_t *' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\game\level\level_editor\label_layer.c(214,23): warning C4477:  'fprintf' : format string '%ld' requires an argument of type 'long', but variadi
c argument 1 has type 'size_t' [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\system\file.c(92,26): warning C4013:  'nth_calloc' undefined; assuming extern returning int [R:\projects\c\nothing\build\nothing.vcxproj]
  R:\projects\c\nothing\src\system\file.c(92,1): warning C4047:  'initializing': 'DIR *' differs in levels of indirection from 'int' [R:\projects\c\nothing\build\nothing.v
cxproj]
  R:\projects\c\nothing\src\system\file.c(112,60): warning C4047:  '=': 'dirent *' differs in levels of indirection from 'int' [R:\projects\c\nothing\build\nothing.vcxproj
]


"R:\projects\c\nothing\build\ALL_BUILD.vcxproj" (default target) (1) ->
"R:\projects\c\nothing\build\nothing_test.vcxproj" (default target) (6) ->
  R:\projects\c\nothing\test\parser_suite.h(33,5): warning C4477:  'fprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'i
ntmax_t' [R:\projects\c\nothing\build\nothing_test.vcxproj]
  R:\projects\c\nothing\test\parser_suite.h(39,5): warning C4477:  'fprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'i
ntmax_t' [R:\projects\c\nothing\build\nothing_test.vcxproj]
  R:\projects\c\nothing\test\parser_suite.h(45,5): warning C4477:  'fprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'i
ntmax_t' [R:\projects\c\nothing\build\nothing_test.vcxproj]
  R:\projects\c\nothing\test\parser_suite.h(73,5): warning C4477:  'fprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'i
ntmax_t' [R:\projects\c\nothing\build\nothing_test.vcxproj]
  R:\projects\c\nothing\test\parser_suite.h(176,1): warning C4477:  'fprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type '
__int64' [R:\projects\c\nothing\build\nothing_test.vcxproj]
```

I'm compiling nothing with
```
elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
  set(CMAKE_C_FLAGS
    "${CMAKE_C_FLAGS} \
    /Wall \
    /WX \
    /wd4201 \
    /wd4204 \
    /wd4255 \
    /wd4668 \
    /wd4710 \
    /wd4777 \
    /wd4820 \
    /wd5045 \
    /D \"_CRT_SECURE_NO_WARNINGS\"")
```

**Comment by RIscRIpt** [comment]
Changes introduced so far: https://github.com/tsoding/nothing/compare/master...RIscRIpt:877
Please note it is still not compile-able.

**Comment by rexim** [comment]
@RIscRIpt Ok, I see. Let's make the code compileable with `\Wall \WX` but with as least warnings disabled as possible (doesn't matter which ones) and as least code modifications as possible (if fixing a warning takes too much time, just disable it). Then we can simply adjust them as we continue developing the project.
